// Theme tokens — single source of truth per component
// Auto-generated by design overhaul — do not inline theme switches

export type AppTheme = 'cozy' | 'neon' | 'dark';

export interface ThemeTokens {
  // Brand
  accent: string;
  accentHover: string;
  accentBg: string;
  accentLight: string;
  accentBorder: string;
  accentMuted: string;
  accentRing: string;

  // Surfaces
  pageBg: string;
  cardBg: string;
  cardBorder: string;
  cardShadow: string;
  cardInteractiveHover: string;

  // Text
  fg: string;
  fgMuted: string;
  fgInverse: string;

  // Navigation
  navActiveBg: string;
  navActiveText: string;
  navInactiveText: string;

  // Dark / overlay
  overlayBg: string;
  overlayText: string;
  overlayMuted: string;

  // Feedback
  successBg: string;
  successText: string;
  errorBg: string;
  errorText: string;
  warningBg: string;
  warningText: string;
}

export const cozyTokens: ThemeTokens = {
  accent: '#DC143C',
  accentHover: '#c91236',
  accentBg: '#FEF2F2',
  accentLight: 'rgba(220, 20, 60, 0.08)',
  accentBorder: '#DC143C',
  accentMuted: '#FFC5C5',
  accentRing: 'rgba(220, 20, 60, 0.15)',

  pageBg: '#F2EFE7',
  cardBg: '#FFF9FA',
  cardBorder: 'rgba(220, 20, 60, 0.16)',
  cardShadow: '0_12px_32px_rgba(73,24,34,0.10)',
  cardInteractiveHover: 'hover:bg-[#DC143C]/[0.035]',

  fg: '#1A1814',
  fgMuted: '#78716C',
  fgInverse: '#FAF9F6',

  navActiveBg: '#DC143C',
  navActiveText: '#FFFFFF',
  navInactiveText: '#78716C',

  overlayBg: '#1A1814',
  overlayText: '#F2EFE7',
  overlayMuted: 'rgba(242,239,231,0.6)',

  successBg: '#22C55E',
  successText: '#16A34A',
  errorBg: '#DC2626',
  errorText: '#DC2626',
  warningBg: '#F59E0B',
  warningText: '#D97706',
};

export const neonTokens: ThemeTokens = {
  accent: '#224334',
  accentHover: '#1A3327',
  accentBg: '#F4FAF0',
  accentLight: 'rgba(156, 229, 193, 0.15)',
  accentBorder: '#224334',
  accentMuted: '#9CE5C1',
  accentRing: 'rgba(34, 67, 52, 0.20)',

  pageBg: '#F4FAF0',
  cardBg: '#FFFFFF',
  cardBorder: 'rgba(34, 67, 52, 0.18)',
  cardShadow: '0_12px_32px_rgba(34,67,52,0.10)',
  cardInteractiveHover: 'hover:bg-[#9CE5C1]/15',

  fg: '#1A1814',
  fgMuted: '#78716C',
  fgInverse: '#F4FAF0',

  navActiveBg: '#9CE5C1',
  navActiveText: '#224334',
  navInactiveText: '#78716C',

  overlayBg: '#1A3328',
  overlayText: '#F4FAF0',
  overlayMuted: 'rgba(244,250,240,0.6)',

  successBg: '#22C55E',
  successText: '#16A34A',
  errorBg: '#DC2626',
  errorText: '#DC2626',
  warningBg: '#F59E0B',
  warningText: '#D97706',
};

export const darkTokens: ThemeTokens = {
  accent: '#F5F5F5',
  accentHover: '#FFFFFF',
  accentBg: '#191919',
  accentLight: 'rgba(255, 255, 255, 0.08)',
  accentBorder: '#F5F5F5',
  accentMuted: '#D4D4D4',
  accentRing: 'rgba(255, 255, 255, 0.28)',

  pageBg: '#080808',
  cardBg: '#111111',
  cardBorder: 'rgba(255, 255, 255, 0.12)',
  cardShadow: '0_16px_48px_rgba(0,0,0,0.42)',
  cardInteractiveHover: 'hover:bg-white/[0.06]',

  fg: '#F5F5F5',
  fgMuted: '#A3A3A3',
  fgInverse: '#080808',

  navActiveBg: '#F5F5F5',
  navActiveText: '#080808',
  navInactiveText: '#A3A3A3',

  overlayBg: '#000000',
  overlayText: '#F5F5F5',
  overlayMuted: 'rgba(245,245,245,0.62)',

  successBg: '#16A34A',
  successText: '#4ADE80',
  errorBg: '#DC2626',
  errorText: '#F87171',
  warningBg: '#D97706',
  warningText: '#FBBF24',
};

export function getThemeTokens(theme: AppTheme): ThemeTokens {
  if (theme === 'dark') return darkTokens;
  return theme === 'neon' ? neonTokens : cozyTokens;
}
